
GET http://localhost:3000/clientes

###
GET http://localhost:3000/clientes/new

###
POST http://localhost:3000/clientes/create
Content-Type: application/json

{
    "nombre": "Carmen",
    "email": "carmen@hotmail.com",
    "edad": 33
}


###
POST http://localhost:3000/clientes/update


